"""empty message

Revision ID: 959bf7fba0cc
Revises: 6bd4e3cb7e56
Create Date: 2020-10-15 14:58:29.604772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959bf7fba0cc'
down_revision = '6bd4e3cb7e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_type_id'], ['encounter_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_security',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('security_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['security_point_id'], ['security_points.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'security_point_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_security',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('security_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['security_point_id'], ['security_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'security_point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_security')
    op.drop_table('user_roles')
    op.drop_table('role_security')
    op.drop_table('encounters')
    op.drop_table('security_points')
    op.drop_table('roles')
    op.drop_table('encounter_types')
    # ### end Alembic commands ###
